
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$all\
$fill\
$sudo \
$time \
$battery
$os \
$hostname\
$container\
$character

"""
# $docker_context
# $hostname\
# $localip


right_format = '' # Don't Like how it formated

# All Default
scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true


[battery]
format = '[$symbol$percentage]($style)'
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰁽 '
unknown_symbol = '󰂃 '
empty_symbol = '󰂎 '

[[battery.display]]
threshold = 30
style = 'bold Red'
[[battery.display]]
threshold = 65
style = 'bold Yellow'
[[battery.display]]
threshold = 100           #Changed on Desktop?
style = 'bold Green'
discharging_symbol = '󰁹 '

[time]
format = '[$time]($style) '
disabled = false

[character]
success_symbol = '[>](bold green) '
error_symbol = '[>](bold green) '

vimcmd_symbol = '[<](bold green)'
vimcmd_replace_one_symbol = '[<](bold purple)'
vimcmd_replace_symbol = '[<](bold purple)'
vimcmd_visual_symbol = '[<](bold yellow)'

[container]
style = 'blue dimmed'
disabled = true       #Here for WSL
symbol = " "

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '…/'
use_os_path_sep = true
read_only = " 󰌾"
read_only_style = 'bold blue'

[docker_context]
only_with_files = false
symbol = " "

[fill]
symbol = ' '

[line_break]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
always_show_remote = false

[git_commit]
tag_symbol = '  '

[git_status] #Needs to be tested
format = '([$ahead_behind]($style))'
disabled = false

[hostname]
format = '[$ssh_symbol]($style) '
ssh_only = true
ssh_symbol = " "
style = 'dimmed cyan'

[localip]
ssh_only = false

[os]
disabled = false
style = 'blue'

[python]
symbol = " "

[sudo]
format = '[sudo]($style)'
style = 'bold red dimmed'
disabled = false

[username]
format = '[$user]($style)'
show_always = false
disabled = true


# Extra Symbols  
[aws]
symbol = " "

[buf]
symbol = ""

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
