color0 #0c141b
color1 #ffb4ab
color2 #4edad3
color3 #80d5cf
color4 #95cdf8
color5 #4edad3
color6 #80d5cf
color7 #dbe3ed
color8 #8293a2
color9 #ffb4ab
color10 #4edad3
color11 #80d5cf
color12 #95cdf8
color13 #4edad3
color14 #80d5cf
color15 #dbe3ed

cursor                #dbe3ed
cursor_text_color     #0c141b
background            #0c141b
foreground            #dbe3ed
selection_foreground  #b7c9d9
selection_background  #384956
active_border_color   #4edad3
inactive_border_color #384956
url_color             #4edad3

active_tab_foreground   #003735
active_tab_background   #4edad3
inactive_tab_foreground #b7c9d9
inactive_tab_background #384956
cursor_trail_color      #b7c9d9
